development: &default
  adapter: sqlite3
  database: 'db/linked_curation_concerns_development.sqlite3'
  pool: <%= ENV.fetch("DB_POOL", 5) %>

test:
  <<: *default
  database: 'db/linked_curation_concerns_test.sqlite3'

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
